import=["~/config/alacritty/keyboard.toml"]
# General config
live_config_reload=true


[window]

dynamic_padding=true
decorations="Full"
opacity=0.9
blur=true
startup_mode="Fullscreen"
title="Mbags Alacritty"
dynamic_title=true
decorations_theme_variant="Dark"

[scrolling]
history=10000
multiplier=5
[mouse]
hide_when_typing=false
[font]
normal={family="MesloLGS NF", style="Regular"}
bold={family="MesloLGS NF", style="Bold"}
italic={family="MesloLGS NF", style="Italic"}
size=16
